# Protolint configuration for AI Pipestream
# Focuses on formatting and auto-fixable style issues

lint:
  rules:
    # Don't use default rules - explicitly specify what we want
    no_default: true

    # Add formatting rules
    add:
      - INDENT
      - ORDER
      - IMPORTS_SORTED
      - PACKAGE_NAME_LOWER_CASE
      - FILE_NAMES_LOWER_SNAKE_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE

  # Directories to exclude from linting
  directories:
    exclude:
      - build
      - vendor
